name: Pylint

on:
  push:
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies and Pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        
    - name: Analysing the code with pylint and handling exit code
      run: |
        pylint --disable=import-error --fail-under 9.5 *.py || 
        pylint_exit=$?
        if [ $pylint_exit -eq 0 ]; then
          echo "Pylint exited with code $pylint_exit"
        else
          echo "Pylint exited with code $pylint_exit"
          exit 1
        fi



